version: "3"
services: 
  database: 
    image: mongo
    container_name: my-mongo-db
    environment: 
      MONGO_INITDB_DATABASE: test-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes: 
      - mongodb:/data/db
    ports: 
      - "27017:27017"

volumes:
  mongodb:
